skillMetadata:
  sections:
    - name: Smart speaker functionality
      fields:
        - type: label
          label: Smart speaker services and functionality
        - type: label
          label: Airplay audio player (v1)
          value: AirPlay is a proprietary protocol stack/suite developed by Apple Inc. that allows wireless streaming between devices of audio, video, device screens, and photos, together with related metadata.
        - name: airplay
          type: checkbox
          label: Enabled
          value: "false"
    - name: MycroftOS system configuration
      fields:
        - type: label
          label: System services
        - type: label
          label: Secure Shell (SSH)
          value: Secure Shell (SSH) is a cryptographic network protocol for operating network services securely over an unsecured network.[1] Typical applications include remote command-line, login, and remote command execution.
        - name: sshd
          type: checkbox
          label: Enabled
          value: "true"
